apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: front
spec:
  replicas: 2
  selector: # le deployement a la main sur les pods qui ont comme label reverse-proxy
    matchLabels:
      app: reverse-proxy # pods qui seront gérés par ce déploiement
  template: # modele du pod
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.1-alpine
